name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 360

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath ./

    - name: Authenticate with ngrok
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create ngrok tunnel to remote desktop
      run: |
        Start-Process .\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 10
        $ngrokUrl = ""
        while ($true) {
          try {
            $tunnels = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
            if ($tunnels.tunnels) {
              $ngrokUrl = $tunnels.tunnels[0].public_url
              Write-Output "ngrok tunnel is available at: $ngrokUrl"
              break
            }
          } catch {
            Write-Output "Waiting for ngrok to initialize..."
            Start-Sleep -Seconds 5
          }
        }
        while ($true) {
          Start-Sleep -Seconds 300
        }
